[package]
name = "contours"
version = "0.1.0"
authors = ["ramiro050 <ramiroleal050@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quickcheck = "0.9"
peroxide = "0.23"
gnuplot = "0.0.37"
